### ISSUE TITLE
0.1 Roadmap

### ISSUE THREAD

**Issue by iamchanii** [dano-inc/react-query-helper#6]
It should be providing a method to create a type-safe hook:
- [x] useQuery
- [x] useInfiniteQuery
- [x] useIsFetching

It should be supporting QueryClient's methods what related with query:
- [x] queryClient.fetchQuery
- [x] queryClient.fetchInfiniteQuery
- [x] queryClient.prefetchQuery
- [x] queryClient.prefetchInfiniteQuery
- [x] queryClient.getQueryData
- [x] queryClient.getQueriesData
- [x] queryClient.setQueryData
- [x] queryClient.getQueryState
- [x] queryClient.setQueriesData
- [x] queryClient.invalidateQueries
- [x] queryClient.refetchQueries
- [x] queryClient.cancelQueries
- [x] queryClient.removeQueries
- [x] queryClient.resetQueries
- [x] queryClient.isFetching

Documentation:
- [x] More examples with CSB

Dogfooding:
> Actually, this library was a part of our project code. as soon as possible, I will replace that codes with this library and want to check production-ready.
- [x] Add some method that related with infinite query
  - [x] getInfiniteQueryData
  - [x] ~getInfiniteQueriesData~
  - [x] setInfiniteQueryData
  - [x] ~setInfiniteQueriesData~
- [x] Migrate our project code (1/2)
- [x] Migrate our project code (2/2)
- [ ] Reduce size?
